# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 506f1698994b247068980dbe0518b25d4580887938d1a4d34f2ed186d534fe08d7745cf671d5671731514e0dc34da2ad993443a9a94fd6c7a3a03eb725be51c6

test:
  secret_key_base: 80ac6b7144f3f23bfdc2998718841c773e82a751d7ddee7863dd4df567050b17973cc1ea468549355cd638a07b7c98534b21d65e224dbca75a3b721d21a0f451

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
